### ISSUE TITLE
Why is Auto-Prepare enforcing that I split / and /home

### ISSUE THREAD

**Issue by tifasoftware** [tpowa/Archboot#2]
After some point in development, Archboot is forcing me to separate / and /home after selecting AUTO-Prepare. When i did this previously, I could have / and /home on the same partition. Now i have to manually partition it to have it on the same partition, because I cannot find a way to tell Auto-prepare to keep it in one partition.

**Comment by tpowa** [comment]
This would  break systemd automounting feature.
Commit: - Auto-Prepare mode is systemd-gpt-auto-generator compliant now
https://www.freedesktop.org/software/systemd/man/systemd-gpt-auto-generator.html
- With Auto-Prepare  I try to give you a most flexible system. 
- /home on a separate partition allows you to switch the distribution easily and you need this for using systemd GPT automounting.

**Comment by tpowa** [comment]
Not a bug it's a feature.
