### ISSUE TITLE
EFI?

### ISSUE THREAD

**Issue by h4rldev** [tpowa/Archboot#3]
Archboot 86_64x doesn't like EFI on VMs.

Is there any way to resolve this?

Edit: I'm gonna try a different ISO, date instead of date-latest

Edit 2: Switching ISO did not help.

**Comment by tpowa** [comment]
Which VM? What is the error? Could you make a video of boot process?

**Comment by h4rldev** [comment]
It doesn't boot, at all on EFI.

I use VirtualBox 7.0.6

[5XI3kgEQl.webm](https://user-images.githubusercontent.com/98224660/223987476-95ae21a6-abbd-4ef7-86f8-11589a442099.webm)
(I hope your browser supports webms because sharex is the only screenrecorder i had on hand.)

**Comment by tpowa** [comment]
Ok have you tried the menu with booting from file or explore fs0: in efi shell

**Comment by h4rldev** [comment]
I haven't, I'll try

**Comment by h4rldev** [comment]
I don't find any EFI file in fs0

**Comment by tpowa** [comment]
Ok your firmware is doing something wrong here.

**Comment by tpowa** [comment]
Ok seems virtualbox has a quite limited iso driver detection.
Will add a fix now that contains the EFIs.

**Comment by tpowa** [comment]
https://gitlab.archlinux.org/tpowa/archboot/-/commit/3ff486eca76fdb9136cbab89bc804ce6a23f6a5b
New fixed images should be up in 45 minutes.
Thanks for the report.
