### ISSUE TITLE
Give the option to have / and /home on seperate partitions or on one

### ISSUE THREAD

**Issue by 0x4248** [tpowa/Archboot#5]
It would be nice if you had the option to have `/` and `/home` on the same partition. Is it possible to have a this on the installer.

**Comment by tpowa** [comment]
Yes sure, go to mountpoint setting and don't use /home and it will be on the / partition.

**Comment by 0x4248** [comment]
<img width="623" alt="Screenshot 2024-08-12 at 7 05 21 PM" src="https://github.com/user-attachments/assets/900d6511-58a4-4f1c-a9a2-ab6c45afd344">
<img width="556" alt="Screenshot 2024-08-12 at 7 05 42 PM" src="https://github.com/user-attachments/assets/3f21171c-50bb-407e-9ea9-d3a2a1493b02">
here?

**Comment by tpowa** [comment]
Yes continue the dialogs and don't use a additional /home and it will be on /.

**Comment by 0x4248** [comment]
<img width="246" alt="Screenshot 2024-08-12 at 7 42 05 PM" src="https://github.com/user-attachments/assets/4b27da30-18bf-45bf-9436-920620d9bc04">

<img width="470" alt="Screenshot 2024-08-12 at 7 42 34 PM" src="https://github.com/user-attachments/assets/0379d89a-3463-4081-b1cc-0bc0a71edd8e">
I format and set PARTLABEL and it cant find my partitions.

**Comment by 0x4248** [comment]
If i manually mount and make the file systems then it works

**Comment by tpowa** [comment]
Well if the partitions are not listed, your vda device contains broken signatures. Next commands will remove all data!
wipefs -a -f /dev/vda
dd if=/dev/zero of=/dev/vda bs=1M count=10
Then start again with partitioning.

**Comment by 0x4248** [comment]
Thanks for the help.
